### ISSUE TITLE
您好大佬，请问代码中哪里体现出mean field理论以及有多个智能体

### ISSUE THREAD

**Issue by wiluen** [MyGithubForReview/Large-Scale-MARL#1]

**Comment by MyGithubForReview** [comment]
代码中未提高执行效率将多个智能体处理为张量的batch，比较难以直观看到。较容易理解的算法请参考我们的文章（已被KDD20223接收，但尚未正式出版，请耐心等待）

**Comment by MyGithubForReview** [comment]
共享网络参数可以减小不同网络参数带来的内存开销，特别是智能体数量很多时。
是的，该方法比较适用于多个智能体的表现较为一致的场景下，多个只能体表现差异大的场景仍具有挑战性。
