### ISSUE TITLE
智能体共享网络参数

### ISSUE THREAD

**Issue by wiluen** [MyGithubForReview/Large-Scale-MARL#2]
感谢上一条的回复，仔细读了您的代码，好像您就是使用了一个网络，这样是否会对场景、智能体的行为有一定限制呢？比如在相同的state下，两个智能体可能做出不一样的动作

**Comment by MyGithubForReview** [comment]
为了减小智能体数目较多场景下网络参数过多，内存开销过大的问题，本文在所有智能体之间共享网络参数。由此，本方法更适用于智能体行为较为一致的场景，而解决智能体行为千差万别场景中的问题仍具有挑战性。

p.s.
1、本文已被KDD‘23接收：https://dl.acm.org/doi/10.1145/3580305.3599359
2、本repo为审稿时临时使用的匿名账号，正式版已迁移至：https://github.com/tsinghua-fib-lab/Large-Scale-MARL-GATMF

**Comment by wiluen** [comment]
thanks
